theme: minima
title: Get to know LTA:)
author: LTA
email: talam0@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi!!! welcome to my page~~

# social links
twitter_username: guess who # DO NOT include the @ character, or else the build will fail!
github_username:  talam0 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
